version: '3.8'

services:
  db:
    image: postgres:13
    environment:
      POSTGRES_DB: biblioteca
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: senha_dev
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./postgres/init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./postgres/conf/pg_hba.conf:/etc/postgresql/pg_hba.conf:ro
      - ./postgres/conf/postgresql.conf:/etc/postgresql/postgresql.conf:ro
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres -d biblioteca" ]
      interval: 10s
      timeout: 5s
      retries: 12
    ports:
      - "5432:5432"

  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    env_file:
      - .env
    volumes:
      - ./:/app                  # hot reload do c√≥digo
    ports:
      - "8080:8080"
    environment:
      - DATABASE_URL=postgresql://postgres:senha_dev@db:5432/biblioteca
    depends_on:
      - db

volumes:
  pgdata:
